spring:
  profiles:
    active: dev  #激活开发环境
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-congig-dev

---
spring:
  profiles: test #测试环境
  application:
<<<<<<< HEAD
    name: microservicecloud-congig-test
=======
    name: microservicecloud-congig-test
>>>>>>> 4502088f7dddf427fddc7a6783d59f8f22135c5c
