spring:
  profiles:
    active: dev  #激活开发环境
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-congig-dev

---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-congig-test