server:
  port: 7001
spring:
  profiles:
    active: dev  #激活开发环境    
---
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    service-url:
      defaultZone:  http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka   #单机  设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
    register-with-eureka: false #表示不像注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
spring:
  profiles: dev
  